#!/usr/bin/env python3
"""Generate approval-gated markdown recommendations from overlap analysis."""
from __future__ import annotations

import datetime as dt
import json
import uuid
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "reports" / "overlap_analysis.json"
OUT_DIR = ROOT / "recommendations"


def today() -> str:
    return dt.datetime.now().strftime("%Y-%m-%d")


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def bucket(candidate: dict) -> str:
    scopes = set(candidate.get("scopes", []))
    cats = set(candidate.get("categories", []))
    if "mcp" in scopes:
        return "mcp-instructions"
    if "skill" in scopes or "telegram-skill" in scopes:
        return "skills-overlap"
    if "global" in scopes:
        return "global-instructions"
    if "project-local" in cats or "project" in scopes:
        return "project-instructions"
    return "general-policy"


def main() -> int:
    data = load_json(ANALYSIS)
    groups = defaultdict(list)
    for c in data.get("candidates", []):
        groups[bucket(c)].append(c)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    run_dir = OUT_DIR / 'runs' / uuid.uuid4().hex
    run_dir.mkdir(parents=True, exist_ok=False)
    written = []
    for name, items in groups.items():
        path = run_dir / f"{name}.md"
        lines = [f"# {name.replace('-', ' ').title()} Recommendations — {today()}", "", "Generated by `scripts/generate_recommendations.py` from local static analysis.", "", "## Guardrail", "", "These are review candidates only. Do not edit target instruction files without explicit approval.", ""]
        for i, c in enumerate(items[:100], 1):
            lines += [f"## {i}. {c['type']} — {c['risk']}", "", f"- Categories: {', '.join(c.get('categories', []))}", f"- Scopes: {', '.join(c.get('scopes', []))}", f"- Suggested edit shape: {c.get('recommendation')}", f"- Approval required: {c.get('approval_required', True)}", f"- Auto-edit allowed: {c.get('auto_edit_allowed', False)}", "", "Evidence:", ""]
            for e in c.get("evidence", [])[:8]:
                loc = f"{e.get('path')}:{e.get('line')}" if e.get("line") else e.get("path")
                lines.append(f"- `{loc}` — {e.get('text', '')[:260]}")
            lines.append("")
        path.write_text("\n".join(lines), encoding="utf-8")
        written.append(path)

    # Always publish an explicit current result, including zero candidates.
    current = {"run": str(run_dir.relative_to(OUT_DIR)), "candidate_count": len(data.get('candidates', [])),
               "files": [str(p.relative_to(OUT_DIR)) for p in written],
               "status": "review-needed", "official_evidence_linked": False,
               "notice": "Older root-level recommendation files are historical, not current results."}
    (OUT_DIR / 'current.json').write_text(json.dumps(current, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    for p in written:
        print(f"wrote {p.relative_to(ROOT)}")
    if not written:
        print("no recommendation groups generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
